version: '3.5'

services:
  postgres:
    image: 'postgres:14'
    container_name: 'postgresql-database'
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=bots_factory_db'